# Generated by Django 2.2.6 on 2019-11-01 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snipp_dogg', '0002_codesnippet_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codesnippet',
            name='source',
        ),
    ]
