# Generated by Django 2.2.6 on 2019-11-01 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snipp_dogg', '0004_auto_20191101_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codesnippet',
            name='language',
            field=models.CharField(choices=[('markup', 'markup'), ('css', 'css'), ('clike', 'clike'), ('javascript', 'javascript'), ('scss', 'scss'), ('python', 'python')], max_length=15),
        ),
    ]
